### PR TITLE
I tried changing up the navbar

### PR DESCRIPTION
**Pull request by Tedejer**
I kinda want to emulate Youtube's navbar with a sidebar. 

image

I'm thinking we can just have it pretty minimal with just a hamburger button and a search box. Probably a profile picture on the right side too.

Right now this is what I made:

image

and this is it expanded

image

This is just implemented on the info page. 
Let me know what you guys think about this compared to the previous one. 

If you want to see it you can just switch to the navbar branch and play around with it.

### CODE REVIEW

**Comment by JerichoPerdon** [comment]
Yeah, I think that looks great. I like the whole drop down feature when you click the Charity Islands text.

**Comment by Tedejer** [comment]
Yea it keeps it pretty simple. The only problem I'm getting is figuring out the searchbox thing. I sort of want it to span the whole center like Youtube. 
Also what do you think about a sidbar nav VS drop-down like I did

**Comment by Tedejer** [comment]
This is how the navbar for Robinhood
image
I also like how this looks

**Review by JeffreyCastillejo — COMMENTED** [review]
Looks good

**Pull request merged**
